### ISSUE TITLE
规范yaml文件格式

### ISSUE THREAD

**Issue by cn-kali-team** [Rvn0xsy/red-tldr-db#10]
- yaml配置文件不规范，有些有#说明有些又没有，还有#开头的命令，就离谱.
- 还有注释说明在命令后面的，复制的时候双击会连中文一起复制了的
- 格式不变，就是把#和说明放在命令的上面，命令后面不要接中文描述
- 你这一输出，我双击把命令**前面的空格**和**后面的中文**一起复制了
- 粘贴进命令行就很难受

**Comment by Rvn0xsy** [comment]
已经进行格式调整
